apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prom-keda
  namespace: prom-keda
  labels:
    release: demo
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: prom-keda
  endpoints:
  - path: /metrics
    port: http
